### PR TITLE
Assorted improvements

### PR DESCRIPTION
**Pull request by LinusU**
- Includes #5 
- Bump all dependencies to the latest version
- Change tested node versions to current (7), LTS (6, 4) and legacy (0.12, 0.10)
- Remove a deprecation warning from the tests
- Use the github repository shorthand in the package.json (sets a few other values such as "website" and "bugs")

### CODE REVIEW

**Comment by alextes** [comment]
Also heads up, tests failed. Not sure why.

**Comment by LinusU** [comment]
Argh, I know why... One needs special config for Travis + Node >=4 + native modules...

Will fix 👌

**Comment by LinusU** [comment]
Rebased on master

**Review by brianc — APPROVED** [review]
👌

**Pull request merged**
